output:
  sort-results: true
linters:
  enable:
    - gofmt
    - goimports
  # prettier-ignore
  disable:
    - tagliatelle      # we're parsing data from external sources (g-rath)
    - varnamelen       # maybe later (g-rath)
    - exhaustruct      # overkill (g-rath)
    - forcetypeassert  # too hard (g-rath)
    - lll              # line length is hard (g-rath)
    - godox            # to-do comments are fine (g-rath)
    - godot            # comments are fine without full stops (g-rath)
    - gomnd            # not every number is magic (g-rath)
    - mnd              # not every number is magic (g-rath)
    - wsl              # disagree with, for now (g-rath)
    - ireturn          # disagree with, sort of (g-rath)
    - gochecknoglobals # disagree with, for non changing variables (another-rex)
    - wrapcheck        # too difficult, will re-add later (another-rex)
    - testpackage      # will re-add later (another-rex)
    - err113           # will re-add later (another-rex)
    - nonamedreturns   # disagree with, for now (another-rex)
    - goconst          # not everything should be a constant
  presets:
    - bugs
    - comment
    - error
    - performance
    - sql
    - style
    - test
    - unused

linters-settings:
  govet:
    settings:
      printf:
        funcs:
          - (github.com/google/osv-scanner/pkg/reporter.Reporter).Errorf
          - (github.com/google/osv-scanner/pkg/reporter.Reporter).Warnf
          - (github.com/google/osv-scanner/pkg/reporter.Reporter).Verbosef
          - (github.com/google/osv-scanner/pkg/reporter.Reporter).Infof
  depguard:
    rules:
      regexp:
        files:
          - "!**/internal/cachedregexp/**"
          - "!**/main_test.go"
        deny:
          - pkg: "regexp"
            desc: "Use github.com/google/osv-scanner/internal/cachedregexp instead"
  gocritic:
    disabled-checks:
      - ifElseChain
  revive:
    rules:
      - name: increment-decrement
        disabled: true
      - name: indent-error-flow
        disabled: false
  nlreturn:
    # Size of the block (including return statement that is still "OK")
    # so no return split required.
    # Default: 1
    block-size: 2

issues:
  exclude-rules:
    - path: pkg/reporter
      linters:
        - dupl
    - path: _test\.go
      linters:
        - dupl
