version: 2

before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/osv-scanner/
    id: osv-scanner-action
    binary: osv-scanner-action
    env:
      # goreleaser does not work with CGO, it could also complicate
      # usage by users in CI/CD systems like Terraform Cloud where
      # they are unable to install libraries.
      - CGO_ENABLED=0
      - GO111MODULE=on
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - "-s -w"
      - "-X github.com/google/osv-scanner/v2/internal/version.OSVVersion={{.Version}}_GHAction"
      - "-X github.com/google/osv-scanner/v2/cmd/osv-scanner/internal/cmd.commit={{.Commit}}"
      - "-X github.com/google/osv-scanner/v2/cmd/osv-scanner/internal/cmd.date={{.CommitDate}}"
    goos:
      - linux
    goarch:
      - amd64
  - main: ./cmd/osv-reporter/
    id: osv-reporter
    binary: osv-reporter
    env: # osv-reporter for github action
      - CGO_ENABLED=0
      - GO111MODULE=on
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - "-s -w"
      - "-X github.com/google/osv-scanner/v2/internal/version.OSVVersion={{.Version}}"
      - "-X github.com/google/osv-scanner/v2/cmd/osv-scanner/internal/cmd.commit={{.Commit}}"
      - "-X github.com/google/osv-scanner/v2/cmd/osv-scanner/internal/cmd.date={{.CommitDate}}"
    goos:
      - linux
    goarch:
      - amd64

dockers:
  # Github Action
  - image_templates:
      - "ghcr.io/google/osv-scanner-action:nightly"
    dockerfile: goreleaser-action.dockerfile
    use: buildx
    extra_files:
      - exit_code_redirect.sh
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.title=osv-scanner-action"
      - "--label=org.opencontainers.image.description=Vulnerability scanner written in Go which uses the data provided by https://osv.dev"
      - "--label=org.opencontainers.image.licenses=Apache-2.0"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=org.opencontainers.image.url={{.GitURL}}"
      - "--platform=linux/amd64"
    goarch: amd64

release:
  disable: true
changelog:
  disable: true
