version: 2

before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/osv-scanner/
    id: osv-scanner
    binary: osv-scanner
    env:
      # goreleaser does not work with CGO, it could also complicate
      # usage by users in CI/CD systems like Terraform Cloud where
      # they are unable to install libraries.
      - CGO_ENABLED=0
      - GO111MODULE=on
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - "-s -w"
      - "-X github.com/google/osv-scanner/v2/internal/version.OSVVersion={{.Version}}.nightly"
      - "-X github.com/google/osv-scanner/v2/cmd/osv-scanner/internal/cmd.commit={{.Commit}}"
      - "-X github.com/google/osv-scanner/v2/cmd/osv-scanner/internal/cmd.date={{.CommitDate}}"
    goos:
      - linux
    goarch:
      - amd64
  - main: ./cmd/osv-scanner/
    id: osv-scanner-action
    binary: osv-scanner-action
    env:
      # goreleaser does not work with CGO, it could also complicate
      # usage by users in CI/CD systems like Terraform Cloud where
      # they are unable to install libraries.
      - CGO_ENABLED=0
      - GO111MODULE=on
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - "-s -w"
      - "-X github.com/google/osv-scanner/v2/internal/version.OSVVersion={{.Version}}.nightly_GHAction"
      - "-X github.com/google/osv-scanner/v2/cmd/osv-scanner/internal/cmd.commit={{.Commit}}"
      - "-X github.com/google/osv-scanner/v2/cmd/osv-scanner/internal/cmd.date={{.CommitDate}}"
    goos:
      - linux
    goarch:
      - amd64
  - main: ./cmd/osv-reporter/
    id: osv-reporter
    binary: osv-reporter
    env: # osv-reporter for github action
      - CGO_ENABLED=0
      - GO111MODULE=on
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - "-s -w"
      - "-X github.com/google/osv-scanner/v2/internal/version.OSVVersion={{.Version}}"
      - "-X github.com/google/osv-scanner/v2/cmd/osv-scanner/internal/cmd.commit={{.Commit}}"
      - "-X github.com/google/osv-scanner/v2/cmd/osv-scanner/internal/cmd.date={{.CommitDate}}"
    goos:
      - linux
    goarch:
      - amd64

dockers_v2:
  # Main osv-scanner
  - id: osv-scanner
    images:
      - "ghcr.io/google/osv-scanner"
    tags:
      - nightly
    dockerfile: goreleaser.dockerfile
    platforms:
      - linux/amd64
    labels:
      org.opencontainers.image.title: osv-scanner
      org.opencontainers.image.description: "Vulnerability scanner written in Go which uses the data provided by https://osv.dev"
      org.opencontainers.image.licenses: Apache-2.0
      org.opencontainers.image.created: "{{.Date}}"
      org.opencontainers.image.name: "{{.ProjectName}}"
      org.opencontainers.image.revision: "{{.FullCommit}}"
      org.opencontainers.image.version: "{{.Version}}"
      org.opencontainers.image.source: "{{.GitURL}}"
      org.opencontainers.image.url: "{{.GitURL}}"
    flags:
      - "--pull"
  # GitHub Action
  - id: osv-scanner-action
    images:
      - "ghcr.io/google/osv-scanner-action"
    tags:
      - nightly
    dockerfile: goreleaser-action.dockerfile
    extra_files:
      - exit_code_redirect.sh
    platforms:
      - linux/amd64
    labels:
      org.opencontainers.image.title: osv-scanner-action
      org.opencontainers.image.description: "Vulnerability scanner written in Go which uses the data provided by https://osv.dev"
      org.opencontainers.image.licenses: Apache-2.0
      org.opencontainers.image.created: "{{.Date}}"
      org.opencontainers.image.name: "{{.ProjectName}}"
      org.opencontainers.image.revision: "{{.FullCommit}}"
      org.opencontainers.image.version: "{{.Version}}"
      org.opencontainers.image.source: "{{.GitURL}}"
      org.opencontainers.image.url: "{{.GitURL}}"
    flags:
      - "--pull"

release:
  disable: true
changelog:
  disable: true
