version: 2

before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/osv-scanner/
    id: osv-scanner
    binary: osv-scanner
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - "-s -w"
      - "-X github.com/google/osv-scanner/v2/internal/version.OSVVersion={{.Version}}"
      - "-X github.com/google/osv-scanner/v2/cmd/osv-scanner/internal/cmd.commit={{.Commit}}"
      - "-X github.com/google/osv-scanner/v2/cmd/osv-scanner/internal/cmd.date={{.CommitDate}}"
    goos:
      - linux
    goarch:
      - amd64

archives:
  - formats: binary
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
    ids:
      - osv-scanner
checksum:
  name_template: "{{ .ProjectName }}_SHA256SUMS"
  algorithm: sha256
release:
  draft: false
  make_latest: true
  replace_existing_artifacts: true
changelog:
  disable: false
