---
- id: osv-scanner
  name: osv-scanner
  description: Scan the current working directory for vulnerabilities
  entry: osv-scanner
  always_run: true
  pass_filenames: false
  language: golang
  args:
    - "scan"
    - "source"
    - "--format=vertical"
    - "--recursive"
    - "--verbosity=error"
    - "."
