source 'https://rubygems.org'

# No groups
platform :ruby do
  gem 'thor', '1.3.2'
end

# Multiple pairs and last is a group
gem 'timeout', '0.4.3', :require => 'websocket-driver', group: 'production'

# Multiple pairs inside hash and second is array of groups
gem 'useragent', # comment to make sure the parser can handle this
  # one more comment to make sure the parser can handle this
  '0.16.11',
  # even one more comment to make sure the parser can handle this
  { :require => 'websocket-driver', :group => [:default,
  # one last comment to make sure the parser can handle this
:production] }

# Group method with block using curly brackets and
#   gem using group without requirement
group(:development) {
  gem 'websocket-driver', group: :ignored
}

# Group method with block using multiple groups,
#   gem without group that will get the external ones and
#   gem with a group that is going to be superseded by the external ones
group :development, :test do
  gem 'websocket-extensions', '0.1.5'
  gem 'zeitwerk', '2.7.1', group: :ignored
end
