source 'https://rubygems.org'

# Bundle edge Rails instead:
gem 'rails', :git => 'https://github.com/rails/rails.git', tag: "v7.1.2"

platforms :ruby do
#  gem 'pg'
  gem 'sqlite3'
end

gem 'jquery-rails'

# Deploy with Capistrano
# gem 'capistrano'

# Bundle the extra gems:
gem 'RedCloth', 
	'~> 4.2.9', # Pessimistic match 
	:require => 'redcloth'

gem 'ruby-openid', :require => 'openid'
gem 'rack-openid', :require => 'rack/openid'
gem 'chronic'
gem 'coderay',
	# Again a pessimistic match 
	'~> 1.0.5'
		# gem 'formtastic'
gem 'will_paginate', '~> 3.0.2'
# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
group :test do
  gem 'database_cleaner'
  gem 'cucumber-rails',    :require => false
  gem 'cucumber-websteps', :require => false
  gem 'factory_girl'
  gem 'rspec'
  gem 'rspec-activemodel-mocks'
  gem 'rspec-collection_matchers'
end

