# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: OSV-Scanner
description: >- # this means to ignore newlines until "baseurl:"
  Use OSV-Scanner to find existing vulnerabilities affecting your project's dependencies.
baseurl: "/osv-scanner" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: google
ga_tracking: G-60SWD6J0TM

# Build settings
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-feed

color_scheme: custom_dark
markdown: kramdown

kramdown:
  toc_levels: 1..3

logo: "/assets/logo-dark.png"
favicon_ico: "/assets/icon.png"

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

aux_links:
  "OSV-Scanner on GitHub":
    - https://github.com/google/osv-scanner

nav_external_links:
  - title: OSV.dev
    url: https://osv.dev
    hide_icon: false # set to true to hide the external link icon - defaults to false
  - title: API docs
    url: https://osv.dev/docs/
    hide_icon: false # set to true to hide the external link icon - defaults to false
  - title: OSV Schema
    url: https://ossf.github.io/osv-schema/
    hide_icon: false # set to true to hide the external link icon - defaults to false

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
