name: Check markdown links

on:
  push:
    paths:
      - "**.md"
  pull_request:
    paths:
      - "**.md"
  schedule:
    - cron: "45 22 * * 1,4"

# Restrict jobs in this workflow to have no permissions by default; permissions
# should be granted per job as needed using a dedicated `permissions` block
permissions: {}

jobs:
  check:
    permissions:
      contents: read # to fetch code (actions/checkout)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: tcort/github-action-markdown-link-check@e047c5b37f24ab722bbef1a27b6fab7f96bc4068 # v1.1.3
        with:
          use-quiet-mode: "yes"
          base-branch: "main"
          check-modified-files-only: ${{ github.event_name == 'schedule' && 'yes' || 'no'}}
