name: Renovate Config Validator

on:
  push:
    branches: [main, v2]
    paths:
      - "renovate.json"
  pull_request:
    branches: [main, v2]
    paths:
      - "renovate.json"

# Restrict jobs in this workflow to have no permissions by default; permissions
# should be granted per job as needed using a dedicated `permissions` block
permissions: {}

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read # to fetch code (actions/checkout)
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Nodes.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: latest

      - name: Validate Renovate Config
        run: npx --yes --package renovate -- renovate-config-validator
